# Latest documentation available at https://omines.github.io/datatables-bundle/#configuration
datatables:

    # Load i18n data from DataTables CDN or locally
    language_from_cdn:    true

    # Default HTTP method to be used for callbacks
    method:               POST # One of "GET"; "POST"

    # Where to persist the current table state automatically
    persist_state:        fragment # One of "none"; "query"; "fragment"; "local"; "session"

    # Default service used to render templates, built-in TwigRenderer uses global Twig environment
    renderer:             Omines\DataTablesBundle\Twig\TwigRenderer

    # Default template to be used for DataTables HTML
    template:             'Template/DataTable/datatableHtml.html.twig'

    # Set options, as documented at https://datatables.net/reference/option/
    options:
        lengthMenu : [10, 25, 50, 100, 250, 500, 1000, 2500]
        pageLength: 50

    template_parameters:
        # Example classes to integrate nicely with Bootstrap 3.x
        className: 'table table-bordered table-hover table-striped w-100 data-table'
        # If and where to enable the DataTables Filter module
        columnFilter: thead # One of "thead"; "tfoot"; "both"; null

    # You can for example override this to "tables" to keep the translation domains separated nicely
    translation_domain: 'messages'
