vich_uploader:
    db_driver: orm

    mappings:
        product_image:
            uri_prefix: /App/File/User
            upload_destination: '%kernel.project_dir%/public/App/File/User'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
